class WellOrdered:
	
	''' A string "aBIY" is said to be a well-ordered 
	word as each of the letters are in sequential manner 
	regardless of case. So, "AbLe" is not a well-ordered 
	word. You are a anti-hacker. you have a number of 
	character sequences. Your task is to generate all 
	possible well-ordered word that can be generated by 
	those numbers of given character sequences.'''
	
	def __init__(self , word):
		self.word = word;

	def displayWord(self):
		print "Word: ",self.word

word1 = WellOrdered("LOL")
word2 = WellOrdered("ROFL")

word1.displayWord()
word2.displayWord()